# Auto-generated by build-report.R
# This file is sourced by all chapter files

library(here)
library(tidyverse)
library(knitr)
library(DBI)
library(RSQLite)
library(readr)

# Define common paths
OUTPUT_DB <<- here('data', 'projects.db')
template_path <<- here('templates', 'project-template.Rmd')

# Source helper functions (contains init_database, get_db_connection, make_bkm)
helper_file <- here('helper-functions', 'helper-functions.R')
if (file.exists(helper_file)) {
  source(helper_file)
  message('✓ Loaded helper functions')
} else {
  stop('❌ helper-functions.R not found at: ', helper_file)
}

# Ensure database exists and is up-to-date
if (!file.exists(OUTPUT_DB)) {
  message('\nDatabase not found. Initializing...')
  init_database(overwrite = TRUE)
} else {
  # Check if database needs updating
  db_status <- check_database(OUTPUT_DB)
  if (db_status$exists) {
    message('✓ Database found: ', db_status$message)
    
    # Verify critical columns exist
    required_cols <- c('project_id', 'source', 'broad_header', 'section', 'include')
    missing <- setdiff(required_cols, db_status$columns)
    if (length(missing) > 0) {
      warning('Database missing required columns: ', paste(missing, collapse=', '))
      message('Rebuilding database...')
      init_database(overwrite = TRUE)
    }
  } else {
    message('Database exists but appears corrupted. Rebuilding...')
    init_database(overwrite = TRUE)
  }
}

# Load project data from database into global environment
if (!exists('projects_df')) {
  tryCatch({
    con <- dbConnect(RSQLite::SQLite(), OUTPUT_DB)
    projects_df <<- dbReadTable(con, 'projects')
    dbDisconnect(con)
    n_projects <<- nrow(projects_df)
    message('✓ Loaded ', n_projects, ' projects from database')
  }, error = function(e) {
    stop('Failed to load projects from database: ', e$message)
  })
}
