# _common.R - Auto-generated by build-report.R
# This file is regenerated on each build but tracked in version control
# so it's available when knitting individual chapters.

# ===================================================================
# Package Loading with Auto-Install
# ===================================================================

# Helper function to install and load packages
ensure_package <- function(pkg) {
  if (!require(pkg, character.only = TRUE, quietly = TRUE)) {
    message('Installing missing package: ', pkg)
    install.packages(pkg, repos = 'https://cloud.r-project.org/')
    library(pkg, character.only = TRUE)
  }
}

# Load required packages
ensure_package('here')
ensure_package('tidyverse')
ensure_package('knitr')
ensure_package('DBI')
ensure_package('RSQLite')
ensure_package('readr')
ensure_package('flextable')
ensure_package('openxlsx')
ensure_package('bookdown')
ensure_package('officer')
ensure_package('officedown')
ensure_package('yaml')

# ===================================================================
# Define Common Paths
# ===================================================================

OUTPUT_DB <<- here('data', 'projects.db')
template_path <<- here('templates', 'project-template.Rmd')
rawdata_path <<- here('data', 'raw')
TABLE_NAME <- "projects"

# ===================================================================
# Source Helper Functions
# ===================================================================

source(here("helper-functions", "helper-functions.R"))

# ===================================================================
# Database Initialization/Validation
# ===================================================================

# Check if database needs updating
db_status <- check_database(OUTPUT_DB)
if (db_status$exists) {
  message('✓ Database found: ', db_status$message)
  
  # Verify critical columns exist
  required_cols <- c('project_id', 'source', 'broad_header', 'section', 'include')
  missing <- setdiff(required_cols, db_status$columns)
  if (length(missing) > 0) {
    warning('Database missing required columns: ', paste(missing, collapse=', '))
    message('Rebuilding database...')
    init_database(overwrite = TRUE)
  }
} else {
  message('Database exists but appears corrupted. Rebuilding...')
  init_database(overwrite = TRUE)
}

# ===================================================================
# Load Project Data into Global Environment
# ===================================================================

if (!exists('projects_df')) {
  tryCatch({
    con <- dbConnect(RSQLite::SQLite(), OUTPUT_DB)
    projects_df <<- dbReadTable(con, 'projects')
    dbDisconnect(con)
    
    # Diagnostic information
    message('✓ Loaded ', nrow(projects_df), ' projects from database')
    message('  Columns: ', paste(names(projects_df), collapse=', '))
    
  }, error = function(e) {
    stop('Failed to load projects from database: ', e$message)
  })
}

# ===================================================================
# Transform Project IDs (with error handling)
# ===================================================================

# Add DFO_ prefix to DFO Science projects for consistent bookmark IDs
tryCatch({
  
  # Verify required columns exist
  if (!"source" %in% names(projects_df)) {
    warning("'source' column not found in database. Skipping project_id transformation.")
  } else if (!"project_id" %in% names(projects_df)) {
    warning("'project_id' column not found in database.")
  } else {
    
    # Ensure columns are character vectors (not lists or other types)
    projects_df$source <- as.character(projects_df$source)
    projects_df$project_id <- as.character(projects_df$project_id)
    
    #Add DFO to project IDs if not already there
    projects_df <- projects_df %>%
      mutate(
        project_id = if_else(
          source == "DFO Science" & !str_starts(project_id, "DFO_"),
          paste0("DFO_", project_id),
          project_id
        )
      )
    
    # Count transformations
    n_transformed <- sum(grepl("^DFO_", projects_df$project_id), na.rm = TRUE)
    message('  Transformed ', n_transformed, ' DFO Science project IDs')
  }
  
}, error = function(e) {
  warning('Error transforming project_id: ', e$message)
  warning('Continuing without transformation...')
})

# ===================================================================
# Set global variable for number of projects
# ===================================================================

n_projects <<- nrow(projects_df)

# ===================================================================
# Knitr Options
# ===================================================================

knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  fig.path = 'figures/generated/'
)

message('\n=== _common.R loaded successfully ===\n')