#!/usr/bin/env Rscript
# build-report.R
# Master script to build PSSI Technical Report
# Note: Run project_report_extraction.R separately to generate project data

library(here)

cat("\n=== PSSI Technical Report Builder ===\n\n")

# Ensure we're in the project directory
project_root <- here::here()
cat("Working directory:", getwd(), "\n")
cat("Project root:", project_root, "\n\n")

# Check if _quarto.yml exists
quarto_config <- file.path(project_root, "_quarto.yml")
if (!file.exists(quarto_config)) {
  stop("\n❌ ERROR: _quarto.yml not found in project root!\n",
       "   Expected at: ", quarto_config, "\n",
       "   Make sure _quarto.yml is in the same directory as your .Rmd files.\n")
}
cat("  ✓ Found _quarto.yml\n\n")

# Step 1: Load helper functions
cat("Step 1: Loading helper functions...\n")
helper_file <- here("helper-functions", "helper-functions.R")

# Create a _common.R file that chapters can source
common_file <- here("_common.R")
cat("# Auto-generated by build-report.R\n",
    "# This file is sourced by all chapter files\n\n",
    "library(here)\n",
    "library(tidyverse)\n",
    "library(knitr)\n",
    "library(DBI)\n",
    "library(RSQLite)\n",
    "library(readr)\n\n",
    "# Define common paths\n",
    "OUTPUT_DB <<- here('data', 'projects.db')\n",
    "OUTPUT_CSV <<- here('data', 'processed', 'pssi_form_data.csv')\n",
    "INPUT_DIR <<- here('data', 'word_docs')\n",
    "template_path <<- here('templates', 'project-template.Rmd')\n\n",
    "# Source helper functions if not already loaded\n",
    "if (!exists('get_db_connection')) {\n",
    "  helper_file <- here('helper-functions', 'helper-functions.R')\n",
    "  if (file.exists(helper_file)) {\n",
    "    source(helper_file)\n",
    "  }\n",
    "}\n\n",
    "# Load project data if not already loaded\n",
    "if (!exists('projects_df')) {\n",
    "  # Try multiple possible CSV locations\n",
    "  csv_paths <- c(\n",
    "    here('data', 'processed', 'pssi_form_data.csv'),\n",
    "    here('data', 'raw', 'report_project_list.csv')\n",
    "  )\n",
    "  \n",
    "  csv_loaded <- FALSE\n",
    "  for (csv_path in csv_paths) {\n",
    "    if (file.exists(csv_path)) {\n",
    "      projects_df <<- read_csv(csv_path, show_col_types = FALSE)\n",
    "      \n",
    "      # Filter based on which columns exist\n",
    "      if ('project_id' %in% names(projects_df)) {\n",
    "        projects_df <<- projects_df %>% filter(!is.na(project_id))\n",
    "      } else if ('project_number' %in% names(projects_df)) {\n",
    "        projects_df <<- projects_df %>% filter(!is.na(project_number))\n",
    "      }\n",
    "      \n",
    "      n_projects <<- nrow(projects_df)\n",
    "      message('Loaded ', n_projects, ' projects from: ', csv_path)\n",
    "      csv_loaded <- TRUE\n",
    "      break\n",
    "    }\n",
    "  }\n",
    "  \n",
    "  if (!csv_loaded) {\n",
    "    warning('No project CSV found in expected locations')\n",
    "    projects_df <<- data.frame()\n",
    "    n_projects <<- 0\n",
    "  }\n",
    "}\n",
    file = common_file, sep = "")
cat("  ✓ Created _common.R for chapters to source\n")

if (file.exists(helper_file)) {
  source(helper_file)
  cat("  ✓ Helper functions loaded from:", helper_file, "\n")
} else {
  cat("  ⚠ helper-functions.R not found at:", helper_file, "\n")
  cat("  Continuing without helper functions...\n")
}

# Step 2: Verify project data exists
cat("\nStep 2: Checking for project data...\n")
db_file <- here("data", "projects.db")
csv_file <- here("data", "processed", "pssi_form_data.csv")

data_found <- FALSE

if (file.exists(db_file)) {
  cat("  ✓ Found project database:", db_file, "\n")
  data_found <- TRUE
  
  # Show database info
  tryCatch({
    con <- dbConnect(RSQLite::SQLite(), db_file)
    if (dbExistsTable(con, "projects")) {
      n_projects <- dbGetQuery(con, "SELECT COUNT(*) as n FROM projects")$n
      cat("    Projects in database:", n_projects, "\n")
    }
    dbDisconnect(con)
  }, error = function(e) {
    cat("    ⚠ Could not read database\n")
  })
}

if (file.exists(csv_file)) {
  cat("  ✓ Found project CSV:", csv_file, "\n")
  data_found <- TRUE
  
  # Show CSV info
  tryCatch({
    csv_data <- read.csv(csv_file)
    cat("    Projects in CSV:", nrow(csv_data), "\n")
  }, error = function(e) {
    cat("    ⚠ Could not read CSV\n")
  })
}

if (!data_found) {
  cat("\n❌ ERROR: No project data found!\n\n")
  cat("To generate project data:\n")
  cat("  1. Place Word documents in: data/word_docs/\n")
  cat("  2. Run: source('project_report_extraction.R')\n")
  cat("  3. Then: extract_all_forms()\n\n")
  stop("Cannot build report without project data")
}

# Step 3: Initialize database (if needed)
cat("\nStep 3: Setting up project database...\n")
if (exists("init_database") && !file.exists(db_file) && file.exists(csv_file)) {
  cat("  Database not found but CSV exists\n")
  cat("  Creating database from CSV...\n")
  tryCatch({
    init_database(overwrite = TRUE)
    cat("  ✓ Database created\n")
  }, error = function(e) {
    cat("  ⚠ Could not create database:", e$message, "\n")
    cat("  Report will use CSV data\n")
  })
} else if (file.exists(db_file) && exists("check_database")) {
  db_status <- check_database()
  if (db_status$exists) {
    cat("  ", db_status$message, "\n")
  }
} else {
  cat("  ⚠ Skipping database setup\n")
}

# Step 4: Render report with Quarto
cat("\nStep 4: Rendering report with Quarto...\n")

# Check if quarto package is installed
if (!requireNamespace("quarto", quietly = TRUE)) {
  cat("  Installing quarto R package...\n")
  install.packages("quarto")
}

library(quarto)

# Change to project directory before rendering (important!)
original_wd <- getwd()
setwd(project_root)

# Render to Word
cat("  Rendering to Word from:", getwd(), "\n")
tryCatch({
  quarto_render(output_format = "docx")
  
  cat("\n✅ Build Complete!\n\n")
  
  # Find the output file in main project folder
  docx_files <- list.files(project_root, pattern = "\\.docx$", full.names = TRUE)
  if (length(docx_files) > 0) {
    cat("✓ Output saved to:", docx_files[1], "\n\n")
  } else {
    cat("⚠ No .docx file found in project root\n\n")
  }
  
}, error = function(e) {
  cat("\n❌ Rendering failed!\n")
  cat("Error:", conditionMessage(e), "\n\n")
  cat("Troubleshooting:\n")
  cat("1. Verify _quarto.yml is in:", project_root, "\n")
  cat("2. Verify index.Rmd exists in:", project_root, "\n")
  cat("3. Check that all chapter files exist\n")
  cat("4. Make sure _common.R was created\n")
  cat("5. Verify project data exists (database or CSV)\n")
  cat("6. Try running manually in R console: quarto::quarto_render()\n\n")
  
  # Restore working directory even on error
  setwd(original_wd)
  stop("Build failed - see error above")
})

# Restore working directory
setwd(original_wd)

cat("=== Build script complete ===\n\n")