#!/usr/bin/env Rscript
# build-report.R
# Master script to build PSSI Technical Report

library(here)

cat("\n=== PSSI Technical Report Builder ===\n\n")

# Ensure we're in the project directory
project_root <- here::here()
cat("Working directory:", getwd(), "\n")
cat("Project root:", project_root, "\n\n")

# Check if _quarto.yml exists
quarto_config <- file.path(project_root, "_quarto.yml")
if (!file.exists(quarto_config)) {
  stop("\n❌ ERROR: _quarto.yml not found in project root!\n",
       "   Expected at: ", quarto_config, "\n",
       "   Make sure _quarto.yml is in the same directory as your .Rmd files.\n")
}
cat("  ✓ Found _quarto.yml\n\n")

# Step 1: Load helper functions
cat("Step 1: Loading helper functions...\n")
helper_file <- here("helper-functions", "helper-functions.R")

if (file.exists(helper_file)) {
  source(helper_file)
  cat("  ✓ Helper functions loaded from:", helper_file, "\n")
} else {
  stop("  ❌ helper-functions.R not found at:", helper_file, "\n")
}

# Step 2: Create _common.R file for chapters
cat("\nStep 2: Creating _common.R for chapters...\n")
common_file <- here("_common.R")

# Write the _common.R file
cat("# Auto-generated by build-report.R\n",
    "# This file is sourced by all chapter files\n\n",
    "library(here)\n",
    "library(tidyverse)\n",
    "library(knitr)\n",
    "library(DBI)\n",
    "library(RSQLite)\n",
    "library(readr)\n\n",
    "# Define common paths\n",
    "OUTPUT_DB <<- here('data', 'projects.db')\n",
    "template_path <<- here('templates', 'project-template.Rmd')\n\n",
    "# Source helper functions (contains init_database, get_db_connection, make_bkm)\n",
    "helper_file <- here('helper-functions', 'helper-functions.R')\n",
    "if (file.exists(helper_file)) {\n",
    "  source(helper_file)\n",
    "  message('✓ Loaded helper functions')\n",
    "} else {\n",
    "  stop('❌ helper-functions.R not found at: ', helper_file)\n",
    "}\n\n",
    "# Ensure database exists and is up-to-date\n",
    "if (!file.exists(OUTPUT_DB)) {\n",
    "  message('\\nDatabase not found. Initializing...')\n",
    "  init_database(overwrite = TRUE)\n",
    "} else {\n",
    "  # Check if database needs updating\n",
    "  db_status <- check_database(OUTPUT_DB)\n",
    "  if (db_status$exists) {\n",
    "    message('✓ Database found: ', db_status$message)\n",
    "    \n",
    "    # Verify critical columns exist\n",
    "    required_cols <- c('project_id', 'source', 'broad_header', 'section', 'include')\n",
    "    missing <- setdiff(required_cols, db_status$columns)\n",
    "    if (length(missing) > 0) {\n",
    "      warning('Database missing required columns: ', paste(missing, collapse=', '))\n",
    "      message('Rebuilding database...')\n",
    "      init_database(overwrite = TRUE)\n",
    "    }\n",
    "  } else {\n",
    "    message('Database exists but appears corrupted. Rebuilding...')\n",
    "    init_database(overwrite = TRUE)\n",
    "  }\n",
    "}\n\n",
    "# Load project data from database into global environment\n",
    "if (!exists('projects_df')) {\n",
    "  tryCatch({\n",
    "    con <- dbConnect(RSQLite::SQLite(), OUTPUT_DB)\n",
    "    projects_df <<- dbReadTable(con, 'projects')\n",
    "    dbDisconnect(con)\n",
    "    n_projects <<- nrow(projects_df)\n",
    "    message('✓ Loaded ', n_projects, ' projects from database')\n",
    "  }, error = function(e) {\n",
    "    stop('Failed to load projects from database: ', e$message)\n",
    "  })\n",
    "}\n",
    file = common_file, sep = "")

cat("  ✓ Created _common.R\n")

# Step 3: Initialize/update database
cat("\nStep 3: Initializing/updating project database...\n")
tryCatch({
  # Check if database needs rebuilding
  if (exists("check_database")) {
    db_status <- check_database()
    if (!db_status$exists) {
      cat("  Database not found, creating new one...\n")
      init_database(overwrite = TRUE)
    } else {
      cat("  ", db_status$message, "\n")
      # Optionally rebuild if CSV files are newer than database
      db_mtime <- file.info(here("data", "projects.db"))$mtime
      csv1_mtime <- file.info(here("report_project_list.csv"))$mtime
      csv2_mtime <- file.info(here("pssi_form_data.csv"))$mtime
      
      if (csv1_mtime > db_mtime || csv2_mtime > db_mtime) {
        cat("  CSV files updated since last build. Rebuilding database...\n")
        init_database(overwrite = TRUE)
      } else {
        cat("  ✓ Database is up-to-date\n")
      }
    }
  }
}, error = function(e) {
  cat("  ⚠ Database initialization failed:", conditionMessage(e), "\n")
  cat("  Attempting to continue...\n")
})

# Step 4: Render report with Quarto
cat("\nStep 4: Rendering report with Quarto...\n")

# Check if quarto package is installed
if (!requireNamespace("quarto", quietly = TRUE)) {
  cat("  Installing quarto R package...\n")
  install.packages("quarto")
}

library(quarto)

# Change to project directory before rendering (important!)
original_wd <- getwd()
setwd(project_root)

# Render to Word
cat("  Rendering to Word from:", getwd(), "\n")
tryCatch({
  quarto_render(output_format = "docx")
  
  cat("\n✅ Build Complete!\n")
  
  # Find the output file
  output_dir <- file.path(project_root, "_book")
  if (dir.exists(output_dir)) {
    docx_files <- list.files(output_dir, pattern = "\\.docx$", full.names = TRUE)
    if (length(docx_files) > 0) {
      cat("Output saved to:", docx_files[1], "\n\n")
    } else {
      cat("Output saved to:", output_dir, "\n\n")
    }
  } else {
    cat("Output saved to: _book/\n\n")
  }
  
}, error = function(e) {
  cat("\n❌ Rendering failed!\n")
  cat("Error:", conditionMessage(e), "\n\n")
  cat("Troubleshooting:\n")
  cat("1. Verify _quarto.yml is in:", project_root, "\n")
  cat("2. Verify index.Rmd exists in:", project_root, "\n")
  cat("3. Check that all chapter files exist\n")
  cat("4. Verify database was created successfully\n")
  cat("5. Check _common.R was created correctly\n")
  cat("6. Try running manually in R console: quarto::quarto_render()\n\n")
  
  # Restore working directory even on error
  setwd(original_wd)
  stop("Build failed - see error above")
})

# Restore working directory
setwd(original_wd)

cat("=== Build script complete ===\n\n")