#!/usr/bin/env Rscript
# build-report.R
# Master script to build PSSI Technical Report

library(here)

cat("\n=== PSSI Technical Report Builder ===\n\n")

# Ensure we're in the project directory
project_root <- here::here()
cat("Working directory:", getwd(), "\n")
cat("Project root:", project_root, "\n\n")

# Check if _quarto.yml exists
quarto_config <- file.path(project_root, "_quarto.yml")
if (!file.exists(quarto_config)) {
  stop("\n✗ ERROR: _quarto.yml not found in project root!\n",
       "   Expected at: ", quarto_config, "\n",
       "   Make sure _quarto.yml is in the same directory as your .Rmd files.\n")
}
cat("  ✓ Found _quarto.yml\n\n")

# Step 1: Create _common.R with standard paths
# FIXED: Removed 'processed' subfolder and 'output' database path
cat("Step 1: Creating _common.R with standard paths...\n")
common_file <- here("_common.R")
cat("# Auto-generated by build-report.R\n",
    "# This file is sourced by all chapter files\n\n",
    "library(here)\n",
    "library(tidyverse)\n",
    "library(knitr)\n",
    "library(DBI)\n",
    "library(RSQLite)\n",
    "library(readr)\n\n",
    "# Define standard paths - data/ folder is the single source of truth\n",
    "OUTPUT_DB <<- here('data', 'projects.db')\n",
    "OUTPUT_CSV <<- here('data', 'processed', 'pssi_form_data.csv')\n", # Fixed: Flat data path
    "INPUT_DIR <<- here('data', 'word_docs')\n",
    "template_path <<- here('templates', 'project-template.Rmd')\n\n",
    "# Alternative template path if templates/ doesn't exist\n",
    "if (!file.exists(template_path)) {\n",
    "  template_path <<- here('project-template.Rmd')\n",
    "}\n\n",
    "# Source helper functions if not already loaded\n",
    "if (!exists('get_db_connection')) {\n",
    "  helper_file <- here('helper-functions', 'helper-functions.R')\n",
    "  if (file.exists(helper_file)) {\n",
    "    source(helper_file)\n",
    "  }\n",
    "}\n\n",
    "# Load project data if not already loaded\n",
    "if (!exists('projects_df')) {\n",
    "  csv_loaded <- FALSE\n",
    "  \n",
    "  # Try loading from database first (preferred - data/projects.db)\n",
    "  if (file.exists(OUTPUT_DB)) {\n",
    "    tryCatch({\n",
    "      con <- dbConnect(SQLite(), OUTPUT_DB)\n",
    "      if ('projects' %in% dbListTables(con)) {\n",
    "        projects_df <<- dbReadTable(con, 'projects')\n",
    "        dbDisconnect(con)\n",
    "        \n",
    "        # Filter out empty rows\n",
    "        if ('project_id' %in% names(projects_df)) {\n",
    "          projects_df <<- projects_df %>% filter(!is.na(project_id))\n",
    "        }\n",
    "        \n",
    "        n_projects <<- nrow(projects_df)\n",
    "        message('Loaded ', n_projects, ' projects from database: ', OUTPUT_DB)\n",
    "        csv_loaded <- TRUE\n",
    "      } else {\n",
    "        dbDisconnect(con)\n",
    "      }\n",
    "    }, error = function(e) {\n",
    "      warning('Failed to load from database: ', e$message)\n",
    "    })\n",
    "  }\n",
    "  \n",
    "  # Fall back to CSV if database didn't work\n",
    "  if (!csv_loaded) {\n",
    "    csv_paths <- c(\n",
    "      OUTPUT_CSV, \n",
    "      here('data', 'pssi_form_data.csv'),\n",
    "      here('pssi_form_data.csv')\n",
    "    )\n",
    "    \n",
    "    for (csv_path in csv_paths) {\n",
    "      if (file.exists(csv_path)) {\n",
    "        tryCatch({\n",
    "          projects_df <<- read_csv(csv_path, show_col_types = FALSE)\n",
    "          \n",
    "          if ('project_id' %in% names(projects_df)) {\n",
    "            projects_df <<- projects_df %>% filter(!is.na(project_id))\n",
    "          } else if ('project_number' %in% names(projects_df)) {\n",
    "            projects_df <<- projects_df %>% filter(!is.na(project_number))\n",
    "          }\n",
    "          \n",
    "          n_projects <<- nrow(projects_df)\n",
    "          message('Loaded ', n_projects, ' projects from CSV: ', csv_path)\n",
    "          csv_loaded <- TRUE\n",
    "          break\n",
    "        }, error = function(e) {\n",
    "          # Continue\n",
    "        })\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "  \n",
    "  if (!csv_loaded) {\n",
    "    warning('No project data found')\n",
    "    projects_df <<- data.frame()\n",
    "    n_projects <<- 0\n",
    "  }\n",
    "}\n",
    file = common_file, sep = "")
cat("  ✓ Created _common.R\n")

# Step 2: Load helper functions
helper_file <- here("helper-functions", "helper-functions.R")
if (file.exists(helper_file)) {
  source(helper_file)
  cat("  ✓ Loaded helper functions\n")
}

# Step 4: Verify database exists
cat("\nStep 3: Verifying database...\n")
db_path <- here('data', 'projects.db') # Standardized
if (file.exists(db_path)) {
  con <- dbConnect(RSQLite::SQLite(), db_path)
  if ("projects" %in% dbListTables(con)) {
    n_rows <- dbGetQuery(con, "SELECT COUNT(*) FROM projects")[[1]]
    cat("  ✓ Database found:", db_path, "\n")
    cat("  ✓ Contains", n_rows, "project(s)\n")
  }
  dbDisconnect(con)
}

# Step 5: Render report with Quarto
cat("\nStep 4: Rendering report with Quarto...\n")
if (!requireNamespace("quarto", quietly = TRUE)) install.packages("quarto")
library(quarto)

original_wd <- getwd()
setwd(project_root)

tryCatch({
  quarto_render(output_format = "docx")
  cat("\n✅ Build Complete!\n")
}, error = function(e) {
  cat("\n✗ Rendering failed!\n")
  stop(e)
})

setwd(original_wd)
cat("=== Build script complete ===\n\n")